// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcCvZbafZb6_uxkqNjpicByP5qV3cL4Rc',
    appId: '1:508417283101:web:c912f18fc9b32b6a0862f4',
    messagingSenderId: '508417283101',
    projectId: 'walltutorial-8a369',
    authDomain: 'walltutorial-8a369.firebaseapp.com',
    storageBucket: 'walltutorial-8a369.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa45rOOVuqGW4UkxeNujX_KCeNAL0ihmQ',
    appId: '1:508417283101:android:a24b54252fee23f80862f4',
    messagingSenderId: '508417283101',
    projectId: 'walltutorial-8a369',
    storageBucket: 'walltutorial-8a369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvS-_xCAqZ_f64vENQgOTmkDp9Wozv0U',
    appId: '1:508417283101:ios:f798b6b00fb571190862f4',
    messagingSenderId: '508417283101',
    projectId: 'walltutorial-8a369',
    storageBucket: 'walltutorial-8a369.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );
}
